### PR TITLE
bumping browserify version to latest

### PR DESCRIPTION
**Pull request by allain**

### CODE REVIEW

**Comment by flesler** [comment]
+1, it's a big bump

**Comment by ForbesLindesay** [comment]
@allain Would you like to be added as a collaborator on this project, to help review and merge pull requests?

**Comment by allain** [comment]
Sure. I'd love that.

**Comment by ForbesLindesay** [comment]
Cool, you're added.  Please follow these rules:

1. never commit directly to master unless you're only editing documentation, or you're in the process of cutting a new release.
2. never merge your own pull request unless it's had no comments from any collaborators for at least 24 hours.
3. If you cut a new release, make sure you update History.md and follow [semver](http://semver.org/) when updating the version number.

If you let me know your npm username I'll add you as an owner so you can release new versions :)

**Comment by allain** [comment]
Will do. My npm username is allain.

**Comment by ForbesLindesay** [comment]
Thanks.  I've added you as an owner.

**Pull request merged**
