### PR TITLE
Pass other options to browserify

### PR DESCRIPTION
**Pull request by refractalize**
> The remaining settings are all passed through to browserify, you should look at the browserify readme if you want to know more:

This works properly for real now

### CODE REVIEW

**Comment by refractalize** [comment]
...bump...

**Comment by refractalize** [comment]
... any comment?

**Comment by mindeavor** [comment]
This should really get merged, especially since it's forward-compatible with future versions of browserify.

**Comment by phjardas** [comment]
could we get this merged please?

**Comment by seggev319** [comment]
@ForbesLindesay Why has this not approved yet?? Its been open for a year and a half now...

**Comment by ForbesLindesay** [comment]
I'm not really actively maintaining this project anymore.  I've added several other collaborators, but ultimately some other people need to review these changes

**Pull request merged**
