### PR TITLE
Fix dynamic caching to prevent rebuilding the whole bundle on every load

### PR DESCRIPTION
**Pull request by scottbrady**
This should fix https://github.com/ForbesLindesay/browserify-middleware/issues/72 and https://github.com/ForbesLindesay/browserify-middleware/issues/68

### CODE REVIEW

**Comment by allain** [comment]
I've installed it locally, ran the tests and it all passes (after changing the timeout for all of the tests to 5 seconds).

Patch itself looks good, I'd probably write getDeps as the following which is equivalent to Object.values, but it's just style.

```js
return Object.keys(dep.deps).map(function (key) {
    return dep.deps[key];
});
```

Nice work!

**Comment by ForbesLindesay** [comment]
I agree we should re-write getDeps to look like Object.values.  I'll fix that up after merge though.

@scottbrady: Would you like to be added as a collaborator on this project, to help review and merge pull requests?

**Comment by scottbrady** [comment]
Thanks for merging the patch so quickly. I'd be happy to help out with pull requests!  Cheers.

**Comment by scottbrady** [comment]
I installed 5.0.1 and I'm now getting this error:

```
TypeError: Object.keys called on non-object
  at Function.keys (native)
  at objectValues (node_modules/browserify-middleware/lib/dynamic-cache.js:7:17)
  at DynamicCache.<anonymous> (node_modules/browserify-middleware/lib/dynamic-cache.js:83:35)
  at Object.oncomplete (fs.js:108:15)
```

I was able to fix the error by adding a type check to the objectValues function:

```
function objectValues(obj) {
  if (typeof obj !== 'object') {
    return [];
  }
  return Object.keys(obj).map(function (key) {
    return obj[key];
  });
}
```

Want me to submit another patch or can you take care of it?

Thanks.

**Comment by allain** [comment]
done

**Comment by scottbrady** [comment]
Thanks @allain!

**Comment by allain** [comment]
@ForbesLindesay Given that this has been fixed can you bump the version on npm?

**Comment by allain** [comment]
When you bring in contributors, you really mean it. I just pushed to npm successfully.

**Comment by ForbesLindesay** [comment]
@scottbrady just saw that I forgot to actually add you as a collaborator.  Should be fixed now :)

Please follow these rules:

1. never commit directly to master unless you're only editing documentation, or you're in the process of cutting a new release.
2. never merge your own pull request unless it's had no comments from any collaborators for at least 24 hours.
3. If you cut a new release, make sure you update History.md and follow [semver](http://semver.org/) when updating the version number.

If you let me know your npm username I'll add you as an owner so you can release new versions :)

@allain Absolutely :+1:.  Without help from people like you, these projects would eventually wither and die from lack of my time.

**Comment by scottbrady** [comment]
@ForbesLindesay I'm scottbrady on npm https://www.npmjs.com/~scottbrady

**Comment by ForbesLindesay** [comment]
Great. I've added you on npm :)

**Pull request merged**
