### PR TITLE
Use watchify for caching

### PR DESCRIPTION
**Pull request by ForbesLindesay**
Maintaining our own dynamic caching system separately from @substack has been a constant source of errors.  Switching to watchify has the downside that we will be polling for changes constantly, rather than just checking for changes when the user hits refresh.  Polling every 100ms should be fine on most people's systems though.  The code looks a little more complex than it might seem like it needs to be because I made watchify notify browserify-middleware immediately of any change so that we can ensure that any requests that come in during the 600ms wait period (that's required to ensure the disk has finished working) are queued until the new bundle is ready.

This also makes caching much simpler by pushing the cached object into being part of the `browserify` handler rather than storing a global mapping between some ID and some cache object.

@adius could you test this out and let me know if it works/if it needs any improvements?
@killroy42 this will implement the async postcompile hook that you requested, via a Promise based interface.
@gabegorelick, @allain & @scottbrady I'd appreciate if one of you could review this change for me and check it all looks sensible to you.  If you are happy with it, feel free to merge and release.

### CODE REVIEW

**Comment by ForbesLindesay** [comment]
I'll merge this today if I don't get any feedback.  Comment now if you want to review this before it's published.

**Comment by adius** [comment]
I'll check it out right now and give feedback

**Comment by gabegorelick** [comment]
No objection from me. I've been thinking for a while that leveraging
watchify makes sense.

**Comment by adius** [comment]
I didn't have any problems … and it is a lot faster. =) Thanks!

**Comment by scottbrady** [comment]
I tested this code on a fairly complex project (~2MB bundle when minified) that uses transforms (Coffeescript, Jade) and everything is working for me.  The new code is definitely much faster.

**Comment by adius** [comment]
So let's merge it?! @ForbesLindesay

**Comment by killroy42** [comment]
Which release will this hit? 10.2.4?

**Pull request merged**
